extern crate lazy_static;
#[macro_use]
extern crate pest_derive;
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
pub mod arm;
pub mod ast;
pub mod cli;
pub mod driver;
pub mod infer_eval;
pub mod ir;
pub mod ir_builder;
pub mod ir_pass;
pub mod ir_printer;
pub mod mc;
pub mod mc_builder;
pub mod mc_inst;
pub mod arm_printer;
pub mod parser;
pub mod scope;
pub mod sema;
pub mod symbol;
pub mod util;
